-- Admin removal of a whole project.
--
-- The panel's import became additive: a workbook that omits a project no longer
-- removes it, which is what stops a corrected upload from silently deleting
-- hundreds of live projects. The cost is that a Project ID typed wrongly into a
-- workbook, once imported, cannot be got rid of by fixing the workbook. This is
-- the way out, and it is administrator-only for the same reason the target
-- delete is.
--
-- "Everything recorded against the project" means all four of these, and the
-- caller does not get to pick a subset - a project whose district survived its
-- own deletion would be worse than either outcome:
--
--   project_targets                 every target, live or archived
--   project_manual_update_audit     project-level AND target-level history
--   project_manual_updates          the hand-typed status/contract/remarks row
--   the imported row itself         removed by the panel from the dataset JSONB,
--                                   which is not a table and cannot be reached
--                                   from SQL - see the note at the end
--
-- Deletion order is forced: project_manual_update_audit.target_id references
-- project_targets(id) with no ON DELETE clause, so the audit rows go first or
-- the target delete raises a foreign-key violation.

-- ---------------------------------------------------------------------------
-- Purge log
-- ---------------------------------------------------------------------------
create table if not exists public.project_purge_log (
  id bigint generated by default as identity primary key,

  -- Every spelling the project's data was filed under. See the note on
  -- p_project_ids below for why this is a list and not one value.
  project_ids text[] not null,
  project_keys text[] not null,

  reason text not null,
  purged_by_uid uuid references auth.users(id) on delete set null,
  purged_by_username text not null,
  purged_at timestamptz not null default now(),

  targets_deleted integer not null,
  audit_rows_deleted integer not null,
  manual_rows_deleted integer not null,

  -- { "targets": [...], "audit": [...], "manual": [...] } verbatim.
  payload jsonb not null
);

create index if not exists project_purge_log_purged_at_idx
  on public.project_purge_log (purged_at desc);

comment on table public.project_purge_log is
  'One row per project destroyed by admin_delete_project(). Holds every deleted target, audit entry and manual-override row verbatim in payload, so a wrong deletion can be reconstructed. Does not cover the imported project row itself, which lives in the project_ledger_dataset JSONB payload and is versioned separately by project_ledger_dataset_versions.';

alter table public.project_purge_log enable row level security;

drop policy if exists "Admins can read the project purge log" on public.project_purge_log;
create policy "Admins can read the project purge log"
  on public.project_purge_log for select
  to authenticated
  using (public.is_project_admin());

revoke all on public.project_purge_log from anon, authenticated;
grant select on public.project_purge_log to authenticated;

-- ---------------------------------------------------------------------------
-- Delete a project and everything filed against it
-- ---------------------------------------------------------------------------
-- p_project_ids is a list because one project's records are not all filed under
-- one string. A project imported before the year became part of the ID has its
-- manual values, audit history and targets stored under the bare "QMB-001",
-- while everything written since is under "QMB-001 - 2025". The panel already
-- resolves which spellings belong to a row - it is the same list it uses to
-- read the audit trail - and passes them here. Deciding it in SQL would mean
-- guessing, and guessing wrong deletes another year's history.
create or replace function public.admin_delete_project(
  p_project_ids text[],
  p_reason      text
)
returns table (
  targets_deleted     integer,
  audit_rows_deleted  integer,
  manual_rows_deleted integer,
  purge_log_id        bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid        uuid := (select auth.uid());
  v_username   text;
  v_keys       text[];
  v_target_ids uuid[];
  v_payload    jsonb;
  v_targets    integer := 0;
  v_audit      integer := 0;
  v_manual     integer := 0;
  v_log_id     bigint;
begin
  if v_uid is null then
    raise exception 'You must be signed in to delete a project.';
  end if;
  if not public.is_project_admin() then
    raise exception 'Only an administrator can delete a project.';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A reason is required. It is the only thing left explaining why this project no longer exists.';
  end if;
  if p_project_ids is null or cardinality(p_project_ids) = 0 then
    raise exception 'No project was named. Nothing was deleted.';
  end if;

  select array_agg(distinct public.project_key(id))
  into v_keys
  from unnest(p_project_ids) as id;

  select p.username into v_username from public.profiles p where p.id = v_uid;
  v_username := coalesce(v_username, 'Unknown user');

  -- Locked before anything is read, so a target created while this runs cannot
  -- survive the delete that was supposed to include it.
  select array_agg(t.id)
  into v_target_ids
  from public.project_targets t
  where t.project_key = any(v_keys)
  for update;

  v_target_ids := coalesce(v_target_ids, array[]::uuid[]);

  -- Captured whole before any of it is destroyed.
  select jsonb_build_object(
    'targets', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.created_at)
      from public.project_targets t where t.project_key = any(v_keys)), '[]'::jsonb),
    'audit', coalesce((
      select jsonb_agg(to_jsonb(a) order by a.id)
      from public.project_manual_update_audit a
      where a.project_id = any(p_project_ids) or a.target_id = any(v_target_ids)), '[]'::jsonb),
    'manual', coalesce((
      select jsonb_agg(to_jsonb(m))
      from public.project_manual_updates m where m.project_id = any(p_project_ids)), '[]'::jsonb)
  )
  into v_payload;

  -- Audit first: the foreign key on target_id forbids the other order. Matched
  -- on the project's own ids AND on the targets being removed, because a target
  -- audit row is filed under whatever project_audit_id() resolved to when it
  -- was written, which is not always one of the ids passed in.
  delete from public.project_manual_update_audit a
  where a.project_id = any(p_project_ids)
     or a.target_id = any(v_target_ids);
  get diagnostics v_audit = row_count;

  delete from public.project_targets t
  where t.project_key = any(v_keys);
  get diagnostics v_targets = row_count;

  delete from public.project_manual_updates m
  where m.project_id = any(p_project_ids);
  get diagnostics v_manual = row_count;

  insert into public.project_purge_log (
    project_ids, project_keys, reason, purged_by_uid, purged_by_username,
    targets_deleted, audit_rows_deleted, manual_rows_deleted, payload
  ) values (
    p_project_ids, v_keys, btrim(p_reason), v_uid, v_username,
    v_targets, v_audit, v_manual, v_payload
  )
  returning id into v_log_id;

  return query select v_targets, v_audit, v_manual, v_log_id;
end;
$$;

comment on function public.admin_delete_project(text[], text) is
  'Permanently deletes every target, audit entry and manual-override row filed under the given project ID spellings, after copying all of them into project_purge_log. Administrators only, checked server-side. Does NOT remove the imported project row: that lives in the project_ledger_dataset JSONB payload and is rewritten by the panel in the same action.';

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
revoke all on function public.admin_delete_project(text[], text) from public, anon;
grant execute on function public.admin_delete_project(text[], text) to authenticated;

-- ---------------------------------------------------------------------------
-- The half this function cannot do
-- ---------------------------------------------------------------------------
-- The imported project - its district, licence, category, location, contract
-- and every other workbook-supplied figure - is not a row in any table. It is
-- an entry in the JSONB payload of project_ledger_dataset, which the browser
-- parses from the workbook and writes back whole. So the panel removes it from
-- that payload and saves the dataset in the same action that calls this
-- function, and the previous payload is kept by project_ledger_dataset_versions
-- exactly as it is for an ordinary import. That is why "Previous data" restores
-- a deleted project's imported values, while this function's purge log is what
-- restores its targets, audit and manual edits.
