-- Developer purge of test targets.
--
-- Every other table here is append-or-archive: nothing is destroyed, because a
-- target that was worked on is a historical fact and its audit trail is the
-- record of who changed what. That stance is correct and is NOT relaxed by this
-- migration. What it adds is a narrow, deliberate exception for one thing the
-- stance cannot handle: input typed while testing the panel, which is not a
-- historical fact about any project and which archiving only hides.
--
-- Three properties keep the exception narrow:
--
--   1. No app role can reach it. EXECUTE is revoked from PUBLIC, anon and
--      authenticated, and nothing grants it back. It runs from the Supabase SQL
--      editor as service_role, or via psql as the owner. A stolen admin session
--      cannot call it, because `authenticated` cannot call it.
--   2. It deletes exactly one target at a time, by primary key, and only the
--      audit rows that belong to that target. Project-level history - Status,
--      Contract, Remarks, and every Excel-updated row - is matched on
--      project_id with a null target_id and is never touched.
--   3. It copies everything into project_target_purge_log before deleting, so
--      a purge run against the wrong UUID is recoverable from the payload.
--
-- Deletion ORDER is not a style choice. project_manual_update_audit.target_id
-- references project_targets(id) with no ON DELETE clause, so the audit rows
-- must go first or the delete raises a foreign-key violation. That constraint
-- is what has been blocking this until now, and it is deliberately left in
-- place: it is the reason a target cannot be destroyed by accident from
-- anywhere else in the system.

-- ---------------------------------------------------------------------------
-- Purge log
-- ---------------------------------------------------------------------------
-- Deleting the audit trail without recording that it happened would leave the
-- database unable to answer "was there ever anything here?", which is the one
-- question an audit trail exists to answer. The log is that answer, and its
-- payload holds the deleted rows verbatim.
create table if not exists public.project_target_purge_log (
  id bigint generated by default as identity primary key,

  -- Plain columns, not references: the rows they name no longer exist. A
  -- foreign key here would be unsatisfiable by construction.
  target_id uuid not null,
  project_id text not null,
  project_key text not null,
  target_scope text,

  reason text not null,
  purged_by text not null,
  purged_at timestamptz not null default now(),

  audit_rows_deleted integer not null,

  -- { "target": {...}, "audit": [ {...}, ... ] } exactly as stored.
  payload jsonb not null
);

create index if not exists project_target_purge_log_target_idx
  on public.project_target_purge_log (target_id);

create index if not exists project_target_purge_log_project_idx
  on public.project_target_purge_log (project_key, purged_at desc);

comment on table public.project_target_purge_log is
  'One row per target destroyed by purge_project_target(). Holds the deleted target and its deleted audit rows verbatim in payload, so a purge run against the wrong UUID can be reconstructed. Not readable by the application: RLS is on and no policy names authenticated, so this is service_role only.';

-- RLS on with no policies at all. For `authenticated` that is a closed door in
-- every direction; service_role bypasses RLS and is the only intended reader.
alter table public.project_target_purge_log enable row level security;

revoke all on public.project_target_purge_log from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Preview
-- ---------------------------------------------------------------------------
-- Read-only, and the intended first step. Deleting by UUID is unforgiving:
-- there is nothing in a UUID to tell a developer they have pasted the wrong
-- one, so the safe move is always to look at what it names first.
create or replace function public.preview_project_target_purge(p_target_id uuid)
returns table (
  target_id uuid,
  project_id text,
  scope text,
  target_qty numeric,
  target_completion date,
  actual_output numeric,
  actual_completion date,
  archived_at timestamptz,
  is_draft boolean,
  has_recorded_delivery boolean,
  audit_rows_to_delete bigint,
  audit_columns text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    t.id,
    t.project_id,
    t.scope,
    t.target_qty,
    t.target_completion,
    t.actual_output,
    t.actual_completion,
    t.archived_at,
    -- Mirrors isTrackable() in src/lib/targets.js: no quantity and no deadline
    -- means there was never anything to measure, which is what test input
    -- normally looks like.
    (t.target_qty is null and t.target_completion is null) as is_draft,
    (t.actual_output is not null or t.actual_completion is not null)
      as has_recorded_delivery,
    (select count(*) from public.project_manual_update_audit a where a.target_id = t.id),
    (select string_agg(distinct a.column_name, ', ' order by a.column_name)
       from public.project_manual_update_audit a where a.target_id = t.id)
  from public.project_targets t
  where t.id = p_target_id;
$$;

comment on function public.preview_project_target_purge(uuid) is
  'Read-only. Shows the target a UUID names and how many audit rows would go with it. Run this before purge_project_target() - a mistyped UUID is otherwise indistinguishable from the right one.';

-- ---------------------------------------------------------------------------
-- Purge
-- ---------------------------------------------------------------------------
-- SECURITY INVOKER, matching every other function in this schema and for the
-- same reason: there is nothing to escalate. The caller is service_role or the
-- owner, both of which already hold DELETE; a definer function would only turn
-- this into a privileged surface that has to be audited separately. Access is
-- controlled by EXECUTE alone, which is revoked from every app role below.
create or replace function public.purge_project_target(
  p_target_id uuid,
  p_reason    text,
  -- Refuses a target carrying recorded delivery unless this is set. Test input
  -- has no actual output and no completion date; something that does is far
  -- more likely to be a real target reached by a wrong UUID.
  p_force     boolean default false
)
returns table (
  purged_target_id  uuid,
  purged_project_id text,
  purged_scope      text,
  audit_rows_deleted integer,
  purge_log_id      bigint
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_target      public.project_targets%rowtype;
  v_audit       jsonb;
  v_audit_count integer;
  v_log_id      bigint;
begin
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A reason is required. It is the only thing left explaining why this data no longer exists.';
  end if;

  -- Locked for the duration: the audit delete and the target delete have to see
  -- the same row, and a concurrent update must not slip between them.
  select * into v_target
  from public.project_targets
  where id = p_target_id
  for update;

  if not found then
    raise exception 'No target has id %. Nothing was deleted.', p_target_id
      using hint = 'Run preview_project_target_purge() first to confirm the UUID.';
  end if;

  if not p_force
     and (v_target.actual_output is not null or v_target.actual_completion is not null) then
    raise exception 'Target % has recorded delivery (actual_output=%, actual_completion=%) and does not look like test input.',
      p_target_id, v_target.actual_output, v_target.actual_completion
      using hint = 'If this really is test data, call it again with p_force => true.';
  end if;

  -- Captured before anything is destroyed, so a purge against the wrong UUID
  -- can be put back from the log.
  select coalesce(jsonb_agg(to_jsonb(a) order by a.id), '[]'::jsonb), count(*)
  into v_audit, v_audit_count
  from public.project_manual_update_audit a
  where a.target_id = p_target_id;

  insert into public.project_target_purge_log (
    target_id, project_id, project_key, target_scope,
    reason, purged_by, audit_rows_deleted, payload
  ) values (
    v_target.id, v_target.project_id, v_target.project_key, v_target.scope,
    btrim(p_reason), current_user, v_audit_count,
    jsonb_build_object('target', to_jsonb(v_target), 'audit', v_audit)
  )
  returning id into v_log_id;

  -- Audit rows first: the foreign key on target_id forbids the other order.
  -- Only rows belonging to THIS target. Project-level history for the same
  -- project carries a null target_id and is not matched here.
  delete from public.project_manual_update_audit a
  where a.target_id = p_target_id;

  delete from public.project_targets t
  where t.id = p_target_id;

  return query
    select v_target.id, v_target.project_id, v_target.scope, v_audit_count, v_log_id;
end;
$$;

comment on function public.purge_project_target(uuid, text, boolean) is
  'Permanently deletes one target and only the audit rows belonging to it, after copying both into project_target_purge_log. Service_role / owner only - EXECUTE is revoked from PUBLIC, anon and authenticated and is never granted back, so no signed-in user, admin included, can reach it. Refuses a target with recorded delivery unless p_force. Project-level audit history is never touched.';

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
-- CREATE FUNCTION grants EXECUTE to PUBLIC by default and anon inherits from
-- PUBLIC, so these revokes are what actually close the door. There is no
-- matching `grant execute ... to authenticated`, and there must never be one:
-- the whole safety argument for this migration is that the application cannot
-- call it.
revoke all on function public.preview_project_target_purge(uuid) from public, anon, authenticated;
revoke all on function public.purge_project_target(uuid, text, boolean) from public, anon, authenticated;

-- The delete privileges the panel deliberately does not have. Restated here so
-- that a project carrying ALTER DEFAULT PRIVILEGES cannot quietly hand DELETE
-- to an app role, and so the intent survives being read in isolation.
revoke delete on public.project_targets from authenticated, anon;
revoke delete on public.project_manual_update_audit from authenticated, anon;
