-- Move every project's existing Remarks text into the Balance Work (scope) of
-- its targets, then clear Remarks so the column is free for new annotations.
--
-- This deliberately reverses the decision recorded in 20260813000000, which
-- declined to seed scope from Remarks because "inventing it from Remarks would
-- merge two fields the business has explicitly separated". The business has now
-- asked for exactly that merge: the text people have been typing into Remarks
-- is, in practice, a description of the balance of work. The earlier comment is
-- left in place as the record of why it was not done then.
--
-- Overwrite, not fill: a target that already has Balance Work text has it
-- replaced. That is the instruction, and it is destructive, so every replaced
-- value is copied into the backup table below first and the change is written
-- to the audit trail. Nothing here is recoverable only from a database dump.
--
-- A project with a remark and no target gets a target created to hold it. An
-- earlier draft skipped those projects instead, on the reasoning that there was
-- nowhere to put the text - but targets only exist where somebody made one or
-- where the 20260813000000 backfill found target data, so "no target" is the
-- common case, not the edge case, and skipping it left most remarks exactly
-- where they were. Creating the target is what makes this migration actually
-- move the data.

-- ---------------------------------------------------------------------------
-- Backup
-- ---------------------------------------------------------------------------
-- One row per target whose scope this migration changes, holding the value it
-- had beforehand. This is what makes the overwrite reversible.
create table if not exists public.project_target_scope_premerge (
  id bigint generated by default as identity primary key,
  target_id uuid not null references public.project_targets(id),
  project_id text not null,
  -- The Balance Work text this migration overwrote. Null means the target had
  -- none, i.e. nothing was lost for that row.
  old_scope text,
  -- What it was overwritten with, so the backup is readable on its own.
  new_scope text not null,
  -- true when this migration created the target as well as its scope, so an
  -- undo knows to archive the row rather than restore a previous value.
  target_created boolean not null default false,
  migrated_at timestamptz not null default now()
);

comment on table public.project_target_scope_premerge is
  'Pre-overwrite copy of project_targets.scope, written once by the Remarks to Balance Work migration. Restore from here if the merge needs undoing; rows where old_scope is null lost nothing, and rows where target_created is true describe targets this migration brought into existence.';

alter table public.project_target_scope_premerge enable row level security;

drop policy if exists "Authenticated users can read scope premerge" on public.project_target_scope_premerge;
create policy "Authenticated users can read scope premerge"
  on public.project_target_scope_premerge for select
  to authenticated
  using (true);

-- Readable, never writable from the API: this is a historical record written
-- once by a migration, and an application that could edit it could destroy the
-- only copy of what the overwrite replaced.
grant select on public.project_target_scope_premerge to authenticated;
revoke all on public.project_target_scope_premerge from anon;

-- ---------------------------------------------------------------------------
-- The move
-- ---------------------------------------------------------------------------
do $$
declare
  batch uuid := gen_random_uuid();
  created_targets int := 0;
  rewritten_targets int := 0;
  cleared_projects int := 0;
begin
  -- Run once. After a successful run every migrated remark is null, so a second
  -- run would find nothing anyway - but a remark typed *after* the migration
  -- would look identical to one typed before it, and moving that would be a
  -- silent data loss the day somebody replays migrations. The marker makes the
  -- run-once guarantee explicit rather than incidental.
  if exists (select 1 from public.project_target_scope_premerge) then
    raise notice 'Remarks to Balance Work migration has already run; nothing to do.';
    return;
  end if;

  -- Every project holding a non-blank remark. Unlike the earlier draft there is
  -- no "and has a target" condition: a project without one gets a target below.
  create temporary table _remarks_move on commit drop as
  select
    m.project_id,
    public.project_key(m.project_id) as project_key,
    btrim(m.remarks)                 as remark,
    m.updated_by
  from public.project_manual_updates m
  where m.remarks is not null
    and btrim(m.remarks) <> '';

  -- ---------------------------------------------------------------------
  -- 1. Projects with no live target: create one to carry the remark.
  -- ---------------------------------------------------------------------
  -- Archived targets do not count as somewhere to put the text - they are
  -- hidden from the panel - so a project holding only archived targets gets a
  -- new live one, which is the correct outcome rather than a duplicate.
  --
  -- migrated_from_project_id is deliberately left null. It carries a unique
  -- index reserved for the 20260813000000 backfill, and reusing it here would
  -- collide with that migration's rows for any project it already touched.
  create temporary table _remarks_new_target on commit drop as
  select r.project_id, r.project_key, r.remark, r.updated_by
  from _remarks_move r
  where not exists (
    select 1
    from public.project_targets t
    where t.project_key = r.project_key
      and t.archived_at is null
  );

  with inserted as (
    insert into public.project_targets (
      project_id, project_key, scope,
      created_by, created_at, updated_by, updated_at
    )
    select n.project_id, n.project_key, n.remark,
           n.updated_by, now(), n.updated_by, now()
    from _remarks_new_target n
    returning id, project_id, scope
  )
  insert into public.project_target_scope_premerge (target_id, project_id, old_scope, new_scope, target_created)
  select i.id, i.project_id, null, i.scope, true
  from inserted i;

  get diagnostics created_targets = row_count;

  -- Audit the creations, matching the shape the target RPCs write.
  insert into public.project_manual_update_audit (
    project_id, target_id, target_scope, column_name, field_key,
    old_value, new_value, action, source, batch_id, changed_by, changed_by_username
  )
  select
    p.project_id, p.target_id, p.new_scope, 'Scope', 'scope',
    null, p.new_scope, 'create', 'migration', batch,
    (select n.updated_by from _remarks_new_target n where n.project_id = p.project_id),
    'System (Remarks to Balance Work migration)'
  from public.project_target_scope_premerge p
  where p.target_created;

  -- ---------------------------------------------------------------------
  -- 2. Projects that already had live targets: overwrite every one of them.
  -- ---------------------------------------------------------------------
  -- Targets created in step 1 are excluded by the backup test - they already
  -- hold the remark, and re-writing them would log a no-op change.
  --
  -- Archived targets are excluded throughout: they are hidden from the panel
  -- and referenced by audit history, so rewriting their scope would corrupt a
  -- historical record to no visible benefit.
  insert into public.project_target_scope_premerge (target_id, project_id, old_scope, new_scope, target_created)
  select t.id, r.project_id, t.scope, r.remark, false
  from public.project_targets t
  join _remarks_move r on r.project_key = t.project_key
  where t.archived_at is null
    and not exists (
      select 1 from public.project_target_scope_premerge p
      where p.target_id = t.id
    );

  -- Audit the target-level change. Field granularity and column naming follow
  -- 20260813000001: 'Scope' is the stored field key the history query matches
  -- on, whatever the column heading says on screen.
  insert into public.project_manual_update_audit (
    project_id, target_id, target_scope, column_name, field_key,
    old_value, new_value, action, source, batch_id, changed_by, changed_by_username
  )
  select
    r.project_id, t.id, r.remark, 'Scope', 'scope',
    t.scope, r.remark, 'update', 'migration', batch, r.updated_by,
    'System (Remarks to Balance Work migration)'
  from public.project_targets t
  join _remarks_move r on r.project_key = t.project_key
  where t.archived_at is null
    and t.scope is distinct from r.remark;

  update public.project_targets t
  set scope      = r.remark,
      updated_by = r.updated_by,
      updated_at = now()
  from _remarks_move r
  where r.project_key = t.project_key
    and t.archived_at is null
    and t.scope is distinct from r.remark;

  get diagnostics rewritten_targets = row_count;

  -- ---------------------------------------------------------------------
  -- 3. Clear Remarks, now that every one of them has landed somewhere.
  -- ---------------------------------------------------------------------
  insert into public.project_manual_update_audit (
    project_id, target_id, target_scope, column_name, field_key,
    old_value, new_value, action, source, batch_id, changed_by, changed_by_username
  )
  select
    r.project_id, null, null, 'Remarks', 'note',
    r.remark, null, 'update', 'migration', batch, r.updated_by,
    'System (Remarks to Balance Work migration)'
  from _remarks_move r;

  update public.project_manual_updates m
  set remarks = null
  from _remarks_move r
  where r.project_id = m.project_id;

  get diagnostics cleared_projects = row_count;

  raise notice 'Remarks to Balance Work: % target(s) created, % existing target(s) rewritten, % project remark(s) cleared.',
    created_targets, rewritten_targets, cleared_projects;
end $$;
