-- Admin deletion of targets and manual audit history, from inside the panel.
--
-- This reverses the schema's founding stance for one role. Everything up to now
-- was append-or-archive, and the reason is written into 20260813000000: an audit
-- row is the record of who changed what, and a target that was worked on is a
-- historical fact. That reasoning has not become wrong. What has changed is the
-- decision: administrators are to be trusted with removing test input at their
-- own end rather than waiting on a developer with database access.
--
-- The consequence is stated plainly so nobody has to rediscover it: a signed-in
-- administrator, or anybody who obtains an administrator's session, can now
-- permanently destroy audit history from a browser. The mitigations below are
-- what keep that bounded. They are not optional extras.
--
--   1. The role check is in the database, not the browser. Hiding a button is
--      not access control - a hidden button is one fetch() away from being
--      pressed. Every function here re-reads the caller's role from profiles
--      and raises if it is not 'admin'.
--   2. No table grant changes. `authenticated` still holds no DELETE on
--      project_targets or project_manual_update_audit, so PostgREST will still
--      refuse a direct DELETE against either table. Deletion exists only
--      through these functions, which is what makes the checks unavoidable.
--      This is the one place in this schema where SECURITY DEFINER is correct,
--      and it is correct precisely because the alternative - granting DELETE to
--      `authenticated` and filtering with an RLS policy - would open the tables
--      to every signed-in user and rely on the policy never being widened.
--   3. Nothing leaves without a record. Every deletion copies the rows it
--      destroys into a purge log, with the acting user, the time and a required
--      reason. The purge log itself has no delete path from the application.

-- ---------------------------------------------------------------------------
-- Who is an administrator
-- ---------------------------------------------------------------------------
-- SECURITY DEFINER so the answer does not depend on the caller being able to
-- read profiles under RLS, and so a future change to the profiles policies
-- cannot silently turn "is this user an admin" into "no rows, so no".
create or replace function public.is_project_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  );
$$;

comment on function public.is_project_admin() is
  'True when the calling user holds role = admin in profiles. Read server-side from auth.uid(); the browser cannot influence the answer.';

revoke all on function public.is_project_admin() from public, anon;
grant execute on function public.is_project_admin() to authenticated;

-- ---------------------------------------------------------------------------
-- Purge log: who deleted what
-- ---------------------------------------------------------------------------
-- project_target_purge_log already exists for the service_role path and is
-- reused, so there is one place to look rather than two. These columns record
-- the acting account, which the service_role path has no concept of.
alter table public.project_target_purge_log
  add column if not exists purged_by_uid uuid references auth.users(id) on delete set null,
  add column if not exists purged_by_username text;

-- Audit rows deleted on their own, rather than as part of removing a target.
create table if not exists public.project_audit_purge_log (
  id bigint generated by default as identity primary key,

  -- Plain columns: the audit row this describes no longer exists.
  audit_id bigint not null,
  project_id text not null,
  column_name text not null,
  target_id uuid,

  reason text not null,
  purged_by_uid uuid references auth.users(id) on delete set null,
  purged_by_username text not null,
  purged_at timestamptz not null default now(),

  -- The deleted row verbatim, so a wrong deletion can be put back.
  payload jsonb not null
);

create index if not exists project_audit_purge_log_project_idx
  on public.project_audit_purge_log (project_id, purged_at desc);

comment on table public.project_audit_purge_log is
  'One row per manual audit entry destroyed by admin_delete_audit_entries(). Holds the deleted row verbatim in payload. Readable by administrators; never writable or deletable from the application.';

alter table public.project_audit_purge_log enable row level security;

-- Administrators can read what was destroyed. Nobody can write or delete it
-- from the application: there is no insert, update or delete policy, and the
-- functions below write to it under SECURITY DEFINER.
drop policy if exists "Admins can read the audit purge log" on public.project_audit_purge_log;
create policy "Admins can read the audit purge log"
  on public.project_audit_purge_log for select
  to authenticated
  using (public.is_project_admin());

revoke all on public.project_audit_purge_log from anon, authenticated;
grant select on public.project_audit_purge_log to authenticated;

-- ---------------------------------------------------------------------------
-- Delete one target, with the audit history belonging to it
-- ---------------------------------------------------------------------------
-- Deleting a target necessarily deletes its audit rows: the foreign key on
-- project_manual_update_audit.target_id has no ON DELETE clause, so the target
-- cannot go while they remain. That is why this is one function and not two -
-- the ordering is a correctness requirement, not a convenience.
--
-- Project-level history is never touched. Status, Contract, Remarks and every
-- Excel-updated row carry a null target_id and are not matched here.
create or replace function public.admin_delete_project_target(
  p_target_id uuid,
  p_reason    text
)
returns table (
  deleted_target_id  uuid,
  deleted_project_id text,
  deleted_scope      text,
  audit_rows_deleted integer,
  purge_log_id       bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid         uuid := (select auth.uid());
  v_username    text;
  v_target      public.project_targets%rowtype;
  v_audit       jsonb;
  v_audit_count integer;
  v_log_id      bigint;
begin
  if v_uid is null then
    raise exception 'You must be signed in to delete a target.';
  end if;
  if not public.is_project_admin() then
    raise exception 'Only an administrator can permanently delete a target. Archive it instead.';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A reason is required. It is the only thing left explaining why this data no longer exists.';
  end if;

  select * into v_target
  from public.project_targets
  where id = p_target_id
  for update;

  if not found then
    raise exception 'That target no longer exists. Reload and try again.';
  end if;

  select p.username into v_username from public.profiles p where p.id = v_uid;
  v_username := coalesce(v_username, 'Unknown user');

  -- Captured before anything is destroyed.
  select coalesce(jsonb_agg(to_jsonb(a) order by a.id), '[]'::jsonb), count(*)
  into v_audit, v_audit_count
  from public.project_manual_update_audit a
  where a.target_id = p_target_id;

  insert into public.project_target_purge_log (
    target_id, project_id, project_key, target_scope,
    reason, purged_by, purged_by_uid, purged_by_username,
    audit_rows_deleted, payload
  ) values (
    v_target.id, v_target.project_id, v_target.project_key, v_target.scope,
    btrim(p_reason), current_user, v_uid, v_username,
    v_audit_count,
    jsonb_build_object('target', to_jsonb(v_target), 'audit', v_audit)
  )
  returning id into v_log_id;

  -- Audit rows first: the foreign key forbids the other order.
  delete from public.project_manual_update_audit a
  where a.target_id = p_target_id;

  delete from public.project_targets t
  where t.id = p_target_id;

  return query
    select v_target.id, v_target.project_id, v_target.scope, v_audit_count, v_log_id;
end;
$$;

comment on function public.admin_delete_project_target(uuid, text) is
  'Permanently deletes one target and the audit rows belonging to it, after copying both into project_target_purge_log. Administrators only, checked server-side. Project-level audit history (null target_id) is never touched.';

-- ---------------------------------------------------------------------------
-- Delete manual audit entries
-- ---------------------------------------------------------------------------
-- Takes an array so that removing one entry and clearing a whole cell's history
-- are the same operation in one transaction. Passing an empty array deletes
-- nothing and is not an error, so a UI that sends the current selection cannot
-- fail merely because the selection was empty.
create or replace function public.admin_delete_audit_entries(
  p_audit_ids bigint[],
  p_reason    text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid      uuid := (select auth.uid());
  v_username text;
  v_deleted  integer;
begin
  if v_uid is null then
    raise exception 'You must be signed in to delete audit history.';
  end if;
  if not public.is_project_admin() then
    raise exception 'Only an administrator can delete audit history.';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A reason is required for deleting audit history.';
  end if;
  if p_audit_ids is null or cardinality(p_audit_ids) = 0 then
    return 0;
  end if;

  select p.username into v_username from public.profiles p where p.id = v_uid;
  v_username := coalesce(v_username, 'Unknown user');

  -- Logged before deletion, and only for rows that actually exist, so the log
  -- never claims something was destroyed that was already gone.
  insert into public.project_audit_purge_log (
    audit_id, project_id, column_name, target_id,
    reason, purged_by_uid, purged_by_username, payload
  )
  select a.id, a.project_id, a.column_name, a.target_id,
         btrim(p_reason), v_uid, v_username, to_jsonb(a)
  from public.project_manual_update_audit a
  where a.id = any(p_audit_ids);

  delete from public.project_manual_update_audit a
  where a.id = any(p_audit_ids);

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

comment on function public.admin_delete_audit_entries(bigint[], text) is
  'Permanently deletes the named manual audit entries after copying each into project_audit_purge_log. Administrators only, checked server-side. An empty array is a no-op returning 0.';

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
-- EXECUTE is granted to `authenticated` because that is the role a signed-in
-- administrator actually holds. The administrator test happens inside each
-- function; a non-admin who calls them gets an exception, not a deletion.
revoke all on function public.admin_delete_project_target(uuid, text) from public, anon;
revoke all on function public.admin_delete_audit_entries(bigint[], text) from public, anon;

grant execute on function public.admin_delete_project_target(uuid, text) to authenticated;
grant execute on function public.admin_delete_audit_entries(bigint[], text) to authenticated;

-- Restated so the intent survives being read in isolation: deletion is reached
-- through the functions above and nowhere else. A direct DELETE from the API,
-- by any signed-in user including an administrator, is still refused.
revoke delete on public.project_targets from authenticated, anon;
revoke delete on public.project_manual_update_audit from authenticated, anon;
revoke all on public.project_target_purge_log from anon;
