-- History for every saved change to an editable project-tracking field.
create table if not exists public.project_manual_update_audit (
  id bigint generated by default as identity primary key,
  project_id text not null references public.project_manual_updates(project_id) on delete cascade,
  column_name text not null,
  old_value text,
  new_value text,
  changed_by uuid not null references auth.users(id) on delete restrict,
  changed_by_username text not null,
  changed_at timestamptz not null default now()
);

create index if not exists project_manual_update_audit_lookup
  on public.project_manual_update_audit (project_id, column_name, changed_at desc);

alter table public.project_manual_update_audit enable row level security;

drop policy if exists "Authenticated users can read project audit" on public.project_manual_update_audit;
create policy "Authenticated users can read project audit"
  on public.project_manual_update_audit for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can insert project audit" on public.project_manual_update_audit;
create policy "Authenticated users can insert project audit"
  on public.project_manual_update_audit for insert
  to authenticated
  with check ((select auth.uid()) = changed_by);

grant select, insert on public.project_manual_update_audit to authenticated;
